apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: ns
spec:
  homepage: https://github.com/ahmetb/kubectx
  shortDescription: Switch between Kubernetes namespaces
  version: {{ .TagName }}
  description: |
    Also known as "kubens", a utility to set your current namespace and switch
    between them.
  caveats: |
    If fzf is installed on your machine, you can interactively choose
    between the entries using the arrow keys, or by fuzzy searching
    as you type.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/ahmetb/kubectx/releases/download/{{ .TagName }}/kubens_{{ .TagName }}_darwin_x86_64.tar.gz" .TagName }}
    bin: kubens
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/ahmetb/kubectx/releases/download/{{ .TagName }}/kubens_{{ .TagName }}_linux_x86_64.tar.gz" .TagName }}
    bin: kubens
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/ahmetb/kubectx/releases/download/{{ .TagName }}/kubens_{{ .TagName }}_windows_x86_64.zip" .TagName }}
    bin: kubens
